plugins:
- stylelint-scss
ignoreFiles:
- './build'
- './dist'
extends:
- stylelint-config-standard
- stylelint-config-standard-scss
rules:
  selector-class-pattern: '^([A-Za-z]*(-|_|$))*'
  selector-id-pattern: '^([A-Za-z]*(-|$))*'